[tool.poetry]
name = "mlstacks"
version = "0.1.0"
packages = [
    { include = "mlstacks", from = "src" },
]
description = "ZenML: Write production-ready ML code."
authors = ["ZenML GmbH <info@zenml.io>"]
readme = "README.md"
homepage = ""
documentation = ""
repository = "https://github.com/zenml-io/mlops-stacks"
license = "Apache-2.0"
keywords = [
    "machine learning", "production", "pipeline", "mlops", "devops"
]


[build-system]
requires = ["setuptools", "wheel"]

# [tool.setuptools]
# package_dir = {"" = "src"}
# packages = "find:"


[tool.pytest.ini_options]
addopts = ["--doctest-modules"]
log_cli = true
log_cli_level = "INFO"
testpaths = "tests"
xfail_strict = true




[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''
/(
	\.git
| \.hg
| \.mypy_cache
| \.tox
| \.venv
| _build
| buck-out
| build
)/
'''

[tool.poetry.dependencies]
pydantic = {version = "2.0b3"}
pyyaml = {version = "6.0"}
click = {version = "8.1.3"}

# dev dependencies
hypothesis = {version = "^6.79.1", optional = true}
pytest = {version = "^7.3.2", optional = true}
mypy = {version = "^1.4.0", optional = true}

