name: Linting & Integration Test

on:
    pull_request:
        branches:
            - main
            - develop
    push:
        branches:
            - main
            - develop

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    ubuntu-setup-python-environment:
        if: github.event.pull_request.draft == false
        strategy:
          matrix:
            os: [ubuntu-latest]
            python-version: ["3.8", "3.9", "3.10", "3.11"]
          fail-fast: false
        uses: ./.github/workflows/setup-python-environment.yml
        with:
          python-version: ${{ matrix.python-version }}
          os: ${{ matrix.os }}
        secrets: inherit

    windows-setup-python-environment:
        if: github.event.pull_request.draft == false
        strategy:
        matrix:
            os: [windows-latest]
            python-version: ["3.8", "3.9", "3.10", "3.11"]
        fail-fast: false
        uses: ./.github/workflows/setup-python-environment.yml
        with:
        python-version: ${{ matrix.python-version }}
        os: ${{ matrix.os }}
        secrets: inherit

    macos-setup-python-environment:
        if: github.event.pull_request.draft == false
        strategy:
        matrix:
            os: [macos-latest]
            python-version: ["3.8", "3.9", "3.10", "3.11"]
        fail-fast: false
        uses: ./.github/workflows/setup-python-environment.yml
        with:
        python-version: ${{ matrix.python-version }}
        os: ${{ matrix.os }}
        secrets: inherit

    ubuntu-lint-unit-test:
        needs: ubuntu-setup-python-environment
        strategy:
        matrix:
            os: [ubuntu-latest]
            python-version: ["3.7", "3.8", "3.9", "3.10"]
        fail-fast: false
        uses: ./.github/workflows/lint-unit-test.yml
        with:
        os: ${{ matrix.os }}
        python-version: ${{ matrix.python-version }}
        secrets: inherit

    windows-lint-unit-test:
        needs: windows-setup-python-environment
        strategy:
        matrix:
            os: [windows-latest]
            python-version: ["3.7", "3.8", "3.9", "3.10"]
        fail-fast: false
        uses: ./.github/workflows/lint-unit-test.yml
        with:
        os: ${{ matrix.os }}
        python-version: ${{ matrix.python-version }}
        secrets: inherit

    macos-lint-unit-test:
        needs: macos-setup-python-environment
        strategy:
        matrix:
            os: [macos-latest]
            python-version: ["3.7", "3.8", "3.9", "3.10"]
        fail-fast: false
        uses: ./.github/workflows/lint-unit-test.yml
        with:
        os: ${{ matrix.os }}
        python-version: ${{ matrix.python-version }}
        secrets: inherit

