name: Test recipes

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop

permissions:
      id-token: write
      contents: read

jobs:
  spell-check:
    name: spell-check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Actions Repository
      uses: actions/checkout@v2

    - name: Spelling checker
      uses: crate-ci/typos@master
      with:
        files: "."
        config: ./.typos.toml

  k3d_test:
    name: k3d_test
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Clone repository
        run: |
          git clone https://github.com/safoinme/mlops-stacks.git
          cd mlops-stacks
          git checkout develop

      #- name: Install k3d
      #  run: |
      #    curl -s https://raw.githubusercontent.com/rancher/k3d/main/install.sh | bash

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.4

      - name: Loop through subdirectories
        run: |
          for dir in $(ls -d */ | grep -Fv -e "modules" -e ".github" | grep "k3d*"); do
            (cd $dir && terraform init)
            (cd $dir && terraform fmt -check)
            (cd $dir && terraform validate)
            (cd $dir && terraform plan -input=false)
          done
