name: Release Package

# Triggers the workflow on push of a tag
on:
  push:
    tags:
      - "*"

jobs:
  lint-unit-test:
    uses: ./.github/workflows/lint-unit-test.yml
    with:
      os: "ubuntu-latest"
      python-version: "3.8"
    secrets: inherit

  publish-python-package:
    needs: lint-unit-test
    uses: ./.github/workflows/publish-pypi-package.yml
    secrets: inherit
